version: '3.7'

networks:
    app-tier:
        driver: bridge
volumes:
    redis_data:

services:
    nodeB:
        image: 'node:16'
        user: 'node'
        working_dir: /home/node/app
        depends_on:
            - ectd
            - redis
        volumes:
            - ./:/home/node/app
        expose:
            - '3000'
        command: 'npm run dev'
        ports:
            - 3000:3000
        networks:
            - app-tier
    nodeA:
        image: 'node:16'
        user: 'node'
        working_dir: /home/node/app
        depends_on:
            - ectd
            - redis
        volumes:
            - ./:/home/node/app
        expose:
            - '3000'
        command: 'npm run dev'
        ports:
            - 4000:3000
        networks:
            - app-tier
    etcd:
        container_name: etcd
        image: 'bitnami/etcd:latest'
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
            - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
        ports:
            - 2379:2379
            - 2380:2380
        networks:
            - app-tier
    redis:
        image: docker.io/bitnami/redis:7.0
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        ports:
            - '6379:6379'
        #        volumes:
        #            - 'redis_data:/bitnami/redis/data'
        networks:
            - app-tier
